import scrapy


class ScrapecentralItem(scrapy.Item):
    md_id = scrapy.Field()
    requested_on = scrapy.Field()
    location = scrapy.Field()
    patient_name = scrapy.Field()
    type = scrapy.Field()
    dates_requested = scrapy.Field()
    first_choice = scrapy.Field()
    second_choice = scrapy.Field()
    general_availability = scrapy.Field()
    patient_note = scrapy.Field()
    titration_history = scrapy.Field()
    dates_requested = scrapy.Field()
    recent_medicine = scrapy.Field()
    uploaded_files = scrapy.Field()

    fname = scrapy.Field()
    lname = scrapy.Field()
    sex = scrapy.Field()
    DOB = scrapy.Field()
    phone = scrapy.Field()
    email = scrapy.Field()
    city = scrapy.Field()
    zip = scrapy.Field()
    state = scrapy.Field()
    prequalifies = scrapy.Field()
    state_residence = scrapy.Field()
    address_data = scrapy.Field()

    phone2 = scrapy.Field()
    prescription_meds = scrapy.Field()
    prescribed = scrapy.Field()
    ins_name = scrapy.Field()
    ins_coverage = scrapy.Field()
    drug_arrest = scrapy.Field()
    current_parole_probation = scrapy.Field()
    rec_date = scrapy.Field()
    rec_state = scrapy.Field()
    prior_rec = scrapy.Field()
    phy_fax_work = scrapy.Field()
    phy_phone_work = scrapy.Field()
    phy_lname = scrapy.Field()
    phy_fname = scrapy.Field()

    treat_last_visit = scrapy.Field()
    current_treat = scrapy.Field()
    onset_yr = scrapy.Field()
    onset_month = scrapy.Field()
    qualify_condition = scrapy.Field()

    med_records = scrapy.Field()
    adult_18 = scrapy.Field()
    valid_identification = scrapy.Field()
    current_NYresident = scrapy.Field()
    general_availability = scrapy.Field()
    address1 = scrapy.Field()
    appointment_type = scrapy.Field()
